- name: PLAY-01
  hosts: frontend
  tasks:
  - name: PLAY-01 and TASK-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-1"
    
  - name: PLAY-01 and TASK-2
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-1"
    
- name: PLAY-02
  hosts: frontend
  tasks:
  - name: PLAY-02 and TASK-1
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-1"
    
  - name: PLAY-02 and TASK-2
    ansible.builtin.debug:
      msg: "Hello from PLAY-01 and TASK-1"
    