- name: varas args
  hosts: local
  connection: local # ansible is connecting to localhost
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course name is:{{ COURSE }} Duration is: {{ DURATION }} Trainer is: {{ TRAINER}}"
