- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: " Hello {{ item }}" # itewm is reserved 
    loop:
    - samson
    - dravid
    - arshadeep
