- name: loops
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print names
    ansible.builtin.package:
      name: "{{ name }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip 