- name: functions
  hosts: local
  connection: local 
  vars:
    name: venkatsai
    gmail: psAI96526@GMAil.com
    ipaddress: "172.31.67.242"
    technologies: devops, linux, azure # string
    tags: # map  or dictionary 
      Application: payment
      Environment: dev
    listtags:
      - key: Application
        value: payment
      - key: Environment
        value: dev
  tasks:
  - name: default variable
    ansible.builtin.debug:
      msg: "name is: {{ name | default('Rohith') }}"

  - name: convert string to list
    ansible.builtin.debug:
      msg: "technologies are: {{ technologies | split(',') }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "tags are: {{ tags | dict2items }}"

  - name: convert list to map 
    ansible.builtin.debug:
      msg: "list tags are: {{ listtags | items2dict }}"

  - name : read yaml file and take it into variables
    ansible.builtin.set_fact:
      my_data: "{{ lookup('file', 'student.yaml') | from_yaml }}"

  - name: convert yaml into json
    ansible.builtin.debug:
      msg: "json format is:{{ my_data | to_json }}"

  - name: save json as file
    ansible.builtin.copy:
      dest: ./data.json
      content: "{{ my_data | to_nice_json  }}"

  - name: convert name into uppercase
    ansible.builtin.debug:
      msg: "name is: {{ name | upper }}"

  - name: convert name into lowercase
    ansible.builtin.debug:
      msg: "gmail is: {{ gmail | lower }}"

  - name: check ipv4 address valid or not
    ansible.builtin.debug:
      msg: "{{ ipaddress | ansible.utils.ipaddr }}"

  - name: grep for root
    # ansible.builtin.command
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: command_output
  
  - name: grep for root
    ansible.builtin.debug:
      msg: "{{ command_output }}"
  
  - name: redirect output
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output
    ignore_errors: true
  
  - name: redirect output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"
  
  - name: redirect output
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output
  
  - name: redirect output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"
  


  

  
  


  




  





  

  